spring.application.name=RechnungFlowService
server.servlet.context-path=/

server.port=8189

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/rechnungflow
spring.datasource.username=postgres
spring.datasource.password=0964273336

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

